### ISSUE TITLE
V3: Serial connection does not work on Windows

### ISSUE THREAD

**Issue by rogerfachini** [techninja/cncserver#105]
When trying to connect to a WaterColorBot on Windows, the connection fails with the error: 
```Error: Reading from COM port (ReadIOCompletion): Operation aborted```

This appears to have been fixed in https://github.com/serialport/node-serialport/pull/1817, so updating node-serialport to v8.0.5 should fix this. After some brief testing it appears that some changes to node-serialport in v8 will require further changes. I'll continue to work on this and submit a PR when I get it working.

**Comment by rogerfachini** [comment]
It looks like #101 should fix this

**Comment by techninja** [comment]
Going to assume this works for now!
