### ISSUE TITLE
Newer serialport?

### ISSUE THREAD

**Issue by arpruss** [techninja/cncserver#97]
I'm wondering if you could upgrade to a newer serialport module? I want to use this with a device that does software handshaking (XON/XOFF), but the 5.0.0 serialport module doesn't support software handshaking on Windows.

**Comment by JohnnyFun** [comment]
I confirmed latest serialport (v8.0.5) works. After updating the package, I just needed to change `cncserver.serial.js` call to `SerialPort.list().then` instead of the old callback syntax. Seems to work.

**Comment by techninja** [comment]
Merged! Thanks guys.
